CREATE ROLE __MIGRATOR_ROLE__ LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '__MIGRATOR_PASSWORD__';
CREATE ROLE __RUNTIME_ROLE__ LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '__RUNTIME_PASSWORD__';
CREATE ROLE __CONTROL_ROLE__ LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '__CONTROL_PASSWORD__';
CREATE ROLE __VERIFIER_ROLE__ LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '__VERIFIER_PASSWORD__';
CREATE ROLE __PROJECTOR_ROLE__ LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '__PROJECTOR_PASSWORD__';
CREATE SCHEMA payops AUTHORIZATION __ADMIN_ROLE__;
